/*
SQLyog Ultimate v12.09 (64 bit)
MySQL - 5.6.39 : Database - examdb
*********************************************************************
*/

/*Table structure for table `t_user` */
CREATE TABLE `t_user` (
  `C_UID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  `C_EF_ID` BIGINT(20) DEFAULT NULL COMMENT '主键',
  `C_WXID` VARCHAR(50) DEFAULT NULL COMMENT '微信ID',
  `C_NICK_NAME` VARCHAR(50) DEFAULT NULL COMMENT '微信昵称',
  `C_SEX` CHAR(1) DEFAULT NULL COMMENT '性别',
  `C_HEAD_IMG` VARCHAR(100) DEFAULT NULL COMMENT '头像路径',
  `C_USER_TYPE` CHAR(1) DEFAULT NULL COMMENT '用户类型',
  `C_CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
  `C_UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`C_UID`),
  KEY `FK_R_A_USER_HAS_A_ERROR_FAVORITES2` (`C_EF_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='用户表';

/*Data for the table `t_user` */

/*Table structure for table `t_course` */
CREATE TABLE `t_course` (
  `C_COURSE_ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `C_COURSE_NAME` VARCHAR(50) DEFAULT NULL COMMENT '课程名称',
  `C_CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
  `C_UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`C_COURSE_ID`)
) ENGINE=INNODB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COMMENT='课程表';

/*Data for the table `t_course` */

/*Table structure for table `t_chapter` */
CREATE TABLE `t_chapter` (
  `C_CH_ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `C_COURSE_ID` BIGINT(20) DEFAULT NULL COMMENT '主键',
  `C_CH_NAME` VARCHAR(50) DEFAULT NULL COMMENT '章节名称',
  `C_COURSE_SORTNUM` INT(11) DEFAULT NULL COMMENT '章节排序编号',
  `C_CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
  `C_UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`C_CH_ID`),
  KEY `FK_R_ONECOURSE_HAS_MORECHAPTERS` (`C_COURSE_ID`),
  CONSTRAINT `FK_R_ONECOURSE_HAS_MORECHAPTERS` FOREIGN KEY (`C_COURSE_ID`) REFERENCES `t_course` (`C_COURSE_ID`)
) ENGINE=INNODB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8 COMMENT='章节表';

/*Data for the table `t_chapter` */

/*Table structure for table `t_exam_place` */

CREATE TABLE `t_exam_place` (
  `C_EP_ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '考点ID',
  `C_CH_ID` BIGINT(20) DEFAULT NULL COMMENT '章节ID',
  `C_EP_NAME` VARCHAR(50) DEFAULT NULL COMMENT '考点名称',
  `C_CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
  `C_UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`C_EP_ID`),
  KEY `FK_R_ONECHAPTER_HAS_MORE_EXAMPLACE` (`C_CH_ID`),
  CONSTRAINT `FK_R_ONECHAPTER_HAS_MORE_EXAMPLACE` FOREIGN KEY (`C_CH_ID`) REFERENCES `t_chapter` (`C_CH_ID`)
) ENGINE=INNODB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COMMENT='考点表';

/*Data for the table `t_exam_place` */
/*Table structure for table `t_question` */
CREATE TABLE `t_question` (
  `C_QUES_ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `C_CH_ID` BIGINT(20) DEFAULT NULL COMMENT '章节ID',
  `C_EP_ID` BIGINT(20) DEFAULT NULL COMMENT '考点ID',
  `C_QUES_TITLE` VARCHAR(200) DEFAULT NULL COMMENT '试题标题正文',
  `C_QUES_TYPE` CHAR(1) DEFAULT NULL COMMENT '试题类型(0 选择题 1 判断题 2 案例题)',
  `C_IS_ENGLISH` CHAR(1) DEFAULT NULL COMMENT '是否英文题',
  `C_CORRECT_OPTION_ID` BIGINT(20) DEFAULT NULL COMMENT '正确选型ID,试题选项表的外键',
  `C_CORRECT_VALUE` CHAR(1) DEFAULT NULL COMMENT '正确内容（判断正误题型的正确答案（0 错误 1正确））',
  `C_CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
  `C_UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`C_QUES_ID`),
  KEY `FK_R_A_EXAM_PLACE_HAS_MORE_QUESTION` (`C_EP_ID`),
  KEY `FK_R_QUESTION_BELONGS_A_CHAPTER` (`C_CH_ID`),
  CONSTRAINT `FK_R_A_EXAM_PLACE_HAS_MORE_QUESTION` FOREIGN KEY (`C_EP_ID`) REFERENCES `t_exam_place` (`C_EP_ID`),
  CONSTRAINT `FK_R_QUESTION_BELONGS_A_CHAPTER` FOREIGN KEY (`C_CH_ID`) REFERENCES `t_chapter` (`C_CH_ID`)
) ENGINE=INNODB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8 COMMENT='试题表';

/*Data for the table `t_question` */

/*Table structure for table `t_question_options` */
CREATE TABLE `t_question_options` (
  `C_QO_ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `C_QUES_ID` BIGINT(20) DEFAULT NULL COMMENT '主键',
  `C_QO_CONTENT` VARCHAR(200) DEFAULT NULL COMMENT '选项内容',
  `C_CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
  `C_UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`C_QO_ID`),
  KEY `FK_R_A_QUESTION_HAS_MORE_SELECTABLE_OPTIONS` (`C_QUES_ID`),
  CONSTRAINT `FK_R_A_QUESTION_HAS_MORE_SELECTABLE_OPTIONS` FOREIGN KEY (`C_QUES_ID`) REFERENCES `t_question` (`C_QUES_ID`)
) ENGINE=INNODB AUTO_INCREMENT=65 DEFAULT CHARSET=utf8 COMMENT='试题选项表';

/*Data for the table `t_question_options` */

/*Table structure for table `t_daily_exam` */
CREATE TABLE `t_daily_exam` (
  `C_DE_ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `C_DE_NAME` VARCHAR(50) DEFAULT NULL COMMENT '每日一练名称',
  `C_DE_DATE` DATE DEFAULT NULL COMMENT '每日一练日期',
  `C_CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
  `C_UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`C_DE_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='每日一练记录表';

/*Data for the table `t_daily_exam` */

/*Table structure for table `t_daily_exam_quetion` */
CREATE TABLE `t_daily_exam_quetion` (
  `C_DE_ID` BIGINT(20) DEFAULT NULL COMMENT '主键',
  `C_QUES_ID` BIGINT(20) DEFAULT NULL COMMENT '主键',
  `C_HQ_SORTNUM` INT(11) DEFAULT NULL COMMENT '题号,从1-75进行编号',
  `C_HQ_OPTIONA` BIGINT(20) DEFAULT NULL COMMENT '选项A编号',
  `C_HQ_OPTIONB` BIGINT(20) DEFAULT NULL COMMENT '选项B编号',
  `C_HQ_OPTIONC` BIGINT(20) DEFAULT NULL COMMENT '选项C编号',
  `C_HQ_OPTIOND` BIGINT(20) DEFAULT NULL COMMENT '选项D编号',
  `C_CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
  `C_UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '更新时间',
  KEY `FK_R_A_DAILY_EXAM_HAS_MORE_QUESTION` (`C_DE_ID`),
  KEY `FK_R_A_QUESTION_BELONGS_MORE_DAILY_EXAM` (`C_QUES_ID`),
  CONSTRAINT `FK_R_A_DAILY_EXAM_HAS_MORE_QUESTION` FOREIGN KEY (`C_DE_ID`) REFERENCES `t_daily_exam` (`C_DE_ID`),
  CONSTRAINT `FK_R_A_QUESTION_BELONGS_MORE_DAILY_EXAM` FOREIGN KEY (`C_QUES_ID`) REFERENCES `t_question` (`C_QUES_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='每日一练试题对应关系表';

/*Data for the table `t_daily_exam_quetion` */

/*Table structure for table `t_error_favorites` */
CREATE TABLE `t_error_favorites` (
  `C_EF_ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `C_UID` BIGINT(20) DEFAULT NULL COMMENT '用户ID',
  `C_EF_TOTAL_NUM` INT(11) DEFAULT NULL COMMENT '收录总数',
  `C_CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
  `C_UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`C_EF_ID`),
  KEY `FK_R_A_USER_HAS_A_ERROR_FAVORITES` (`C_UID`),
  CONSTRAINT `FK_R_A_USER_HAS_A_ERROR_FAVORITES` FOREIGN KEY (`C_UID`) REFERENCES `t_user` (`C_UID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='错题收藏夹表';

/*Data for the table `t_error_favorites` */

/*Table structure for table `t_error_favorites_details` */
CREATE TABLE `t_error_favorites_details` (
  `C_EFD_ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '收藏夹试题收录ID',
  `C_QUES_ID` BIGINT(20) DEFAULT NULL COMMENT '主键',
  `C_EF_ID` BIGINT(20) DEFAULT NULL COMMENT '主键',
  `C_EFD_OPTIONA` BIGINT(20) DEFAULT NULL COMMENT '选项A编号',
  `C_EFD_OPTIONB` BIGINT(20) DEFAULT NULL COMMENT '选项B编号',
  `C_EFD_OPTIONC` BIGINT(20) DEFAULT NULL COMMENT '选项C编号',
  `C_EFD_OPTIOND` BIGINT(20) DEFAULT NULL COMMENT '选项D编号',
  `C_EFD_CHOOSED` BIGINT(20) DEFAULT NULL COMMENT '作答选项编号',
  `C_CREATE_TIME` DATETIME DEFAULT NULL COMMENT '记录创建时间',
  `C_UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '记录更新时间',
  PRIMARY KEY (`C_EFD_ID`),
  KEY `FK_R_A_ERROR_FAVORITES_HAS_MORE_ERROR_FAVORITES_DETAILS` (`C_EF_ID`),
  KEY `FK_R_A_QUESTION_BELONGS_MORE_ERROR_FAVORITES_DETAILS` (`C_QUES_ID`),
  CONSTRAINT `FK_R_A_ERROR_FAVORITES_HAS_MORE_ERROR_FAVORITES_DETAILS` FOREIGN KEY (`C_EF_ID`) REFERENCES `t_error_favorites` (`C_EF_ID`),
  CONSTRAINT `FK_R_A_QUESTION_BELONGS_MORE_ERROR_FAVORITES_DETAILS` FOREIGN KEY (`C_QUES_ID`) REFERENCES `t_question` (`C_QUES_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='错题收藏夹试题明细表';

/*Data for the table `t_error_favorites_details` */


/*Table structure for table `t_exercises_record` */
CREATE TABLE `t_exercises_record` (
  `C_ER_ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `C_UID` BIGINT(20) DEFAULT NULL COMMENT '用户ID',
  `C_ER_TYPE` CHAR(1) DEFAULT NULL COMMENT '作答类型',
  `C_ER_QUESTION_ID` BIGINT(20) DEFAULT NULL COMMENT '题目ID-根据作答类型匹配不同的题目,每日一练关联t_daily_exam表,真题演练关联历年真题表（t_history_actual_combat）',
  `C_ER_QUESTION_NUMS` INT(11) DEFAULT NULL COMMENT '总题目数量',
  `C_ER_TRUE_NUMS` INT(11) DEFAULT NULL COMMENT '正确作答数量',
  `C_ER_FALSE_NUMS` INT(11) DEFAULT NULL COMMENT '错误作答数量',
  `C_DER_SCORE` INT(11) DEFAULT NULL COMMENT '得分',
  `C_DER_ACCURACY` DECIMAL(8,2) DEFAULT NULL COMMENT '正确率',
  `C_RESULT` VARCHAR(200) DEFAULT NULL COMMENT '作答结果（将正确的答案选项编号通过英文逗号拼接）',
  `C_CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
  `C_UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`C_ER_ID`),
  KEY `FK_R_A_USER_HAS_MORE_EXERCISES_RECORD` (`C_UID`),
  CONSTRAINT `FK_R_A_USER_HAS_MORE_EXERCISES_RECORD` FOREIGN KEY (`C_UID`) REFERENCES `t_user` (`C_UID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='答题记录表';

/*Data for the table `t_exercises_record` */


/*Table structure for table `t_history_actual_combat` */
CREATE TABLE `t_history_actual_combat` (
  `C_HAC_ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '历年真题ID，主键',
  `C_HAC_NAME` VARCHAR(50) DEFAULT NULL COMMENT '真题名称',
  `C_HAC_DATE` DATE DEFAULT NULL COMMENT '考试日期',
  `C_HAC_TIME` VARCHAR(50) DEFAULT NULL COMMENT '考试时间范围',
  `C_CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
  `C_UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`C_HAC_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='历年真题表';

/*Data for the table `t_history_actual_combat` */

/*Table structure for table `t_hac_question` */
CREATE TABLE `t_hac_question` (
  `C_QUES_ID` BIGINT(20) DEFAULT NULL COMMENT '主键',
  `C_HAC_ID` BIGINT(20) DEFAULT NULL COMMENT '历年真题ID，主键',
  `C_HQ_SORTNUM` INT(11) DEFAULT NULL COMMENT '题号,从1-75进行编号',
  `C_HQ_OPTIONA` BIGINT(20) DEFAULT NULL COMMENT '选项A编号',
  `C_HQ_OPTIONB` BIGINT(20) DEFAULT NULL COMMENT '选项B编号',
  `C_HQ_OPTIONC` BIGINT(20) DEFAULT NULL COMMENT '选项C编号',
  `C_HQ_OPTIOND` BIGINT(20) DEFAULT NULL COMMENT '选项D编号',
  `C_CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
  `C_UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '更新时间',
  KEY `FK_R_A_HISTORY_ACTUAL_COMBAT_HAS_MORE_QUESTION` (`C_HAC_ID`),
  KEY `FK_R_A_QUESTION_HAS_MORE_HAC` (`C_QUES_ID`),
  CONSTRAINT `FK_R_A_HISTORY_ACTUAL_COMBAT_HAS_MORE_QUESTION` FOREIGN KEY (`C_HAC_ID`) REFERENCES `t_history_actual_combat` (`C_HAC_ID`),
  CONSTRAINT `FK_R_A_QUESTION_HAS_MORE_HAC` FOREIGN KEY (`C_QUES_ID`) REFERENCES `t_question` (`C_QUES_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='真题试题对应关系表\n设计时需考虑真题的选项固定的问题（增加4个字段，分别对应ABCD个选项的编号）。';

/*Data for the table `t_hac_question` */


/*Table structure for table `t_order` */
CREATE TABLE `t_order` (
  `C_ORDER_ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `C_UID` BIGINT(20) DEFAULT NULL COMMENT '用户ID',
  `C_COURSE_ID` BIGINT(20) DEFAULT NULL COMMENT '主键',
  `C_ORDER_AMOUNT` DECIMAL(8,2) DEFAULT NULL COMMENT '订单金额',
  `C_ORDER_PAY_TYPE` CHAR(1) DEFAULT NULL COMMENT '支付方式',
  `C_PERMISSION_LEVEL` DATE DEFAULT NULL COMMENT '权限级别',
  `C_CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
  `C_UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`C_ORDER_ID`),
  KEY `FK_R_A_ORDER_HAS_MORE_COURSE` (`C_COURSE_ID`),
  KEY `FK_R_A_USER_HAS_MORE_ORDER` (`C_UID`),
  CONSTRAINT `FK_R_A_ORDER_HAS_MORE_COURSE` FOREIGN KEY (`C_COURSE_ID`) REFERENCES `t_course` (`C_COURSE_ID`),
  CONSTRAINT `FK_R_A_USER_HAS_MORE_ORDER` FOREIGN KEY (`C_UID`) REFERENCES `t_user` (`C_UID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='订单表';

/*Data for the table `t_order` */

/*Table structure for table `t_permission` */
CREATE TABLE `t_permission` (
  `C_PERM_ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '权限ID',
  `C_PERM_NAME` VARCHAR(50) DEFAULT NULL COMMENT '权限名称',
  `C_PERM_TYPE` CHAR(1) DEFAULT NULL COMMENT '权限类型',
  `C_PERM_URL` VARCHAR(100) DEFAULT NULL COMMENT '权限对应的URL',
  `C_PERM_PID` BIGINT(20) DEFAULT NULL COMMENT '父权限ID',
  `C_CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
  `C_UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`C_PERM_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='权限表';

/*Data for the table `t_permission` */


/*Table structure for table `t_question_discuss` */
CREATE TABLE `t_question_discuss` (
  `C_QD_ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `C_UID` BIGINT(20) DEFAULT NULL COMMENT '用户ID',
  `C_QUES_ID` BIGINT(20) DEFAULT NULL COMMENT '主键',
  `C_QD_CONTENT` VARCHAR(200) DEFAULT NULL COMMENT '评论内容',
  `C_CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
  `C_UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`C_QD_ID`),
  KEY `FK_R_A_QUESTION_HAS_MORE_DISCUSS` (`C_QUES_ID`),
  KEY `FK_R_A_USER_HAS_MORE_QUESTION_DISCUSS` (`C_UID`),
  CONSTRAINT `FK_R_A_QUESTION_HAS_MORE_DISCUSS` FOREIGN KEY (`C_QUES_ID`) REFERENCES `t_question` (`C_QUES_ID`),
  CONSTRAINT `FK_R_A_USER_HAS_MORE_QUESTION_DISCUSS` FOREIGN KEY (`C_UID`) REFERENCES `t_user` (`C_UID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='试题评论表';

/*Data for the table `t_question_discuss` */

/*Table structure for table `t_role` */
CREATE TABLE `t_role` (
  `C_ROLE_ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '角色ID ',
  `C_ROLE_NAME` VARCHAR(50) DEFAULT NULL COMMENT '角色名称',
  `C_CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
  `C_UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`C_ROLE_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='角色表';

/*Data for the table `t_role` */

/*Table structure for table `t_role_permission` */
CREATE TABLE `t_role_permission` (
  `C_PERM_ID` BIGINT(20) NOT NULL COMMENT '权限ID',
  `C_ROLE_ID` BIGINT(20) NOT NULL COMMENT '角色ID ',
  PRIMARY KEY (`C_PERM_ID`,`C_ROLE_ID`),
  KEY `FK_T_ROLE_PERMISSION2` (`C_ROLE_ID`),
  CONSTRAINT `FK_T_ROLE_PERMISSION` FOREIGN KEY (`C_PERM_ID`) REFERENCES `t_permission` (`C_PERM_ID`),
  CONSTRAINT `FK_T_ROLE_PERMISSION2` FOREIGN KEY (`C_ROLE_ID`) REFERENCES `t_role` (`C_ROLE_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

/*Data for the table `t_role_permission` */



/*Table structure for table `t_user_role` */
CREATE TABLE `t_user_role` (
  `C_UID` BIGINT(20) NOT NULL COMMENT '用户ID',
  `C_ROLE_ID` BIGINT(20) NOT NULL COMMENT '角色ID ',
  PRIMARY KEY (`C_UID`,`C_ROLE_ID`),
  KEY `FK_T_USER_ROLE2` (`C_ROLE_ID`),
  CONSTRAINT `FK_T_USER_ROLE` FOREIGN KEY (`C_UID`) REFERENCES `t_user` (`C_UID`),
  CONSTRAINT `FK_T_USER_ROLE2` FOREIGN KEY (`C_ROLE_ID`) REFERENCES `t_role` (`C_ROLE_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='用户角色关系表';
